name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "fb84535268b34c5abd15b355854c16b5" },
  { binding = "SHARE", id = "2a2b137160bc44299d50edda962a8d14" }
]